- block:
    - name: Obtain SSO token
      ovirt_auth:
          url: "{{ vars['dr_sites_' + dr_target_host + '_url'] }}"
          username: "{{ vars['dr_sites_' + dr_target_host + '_username'] }}"
          password: "{{ vars['dr_sites_' + dr_target_host + '_password'] }}"
          ca_file: "{{ vars['dr_sites_' + dr_target_host + '_ca_file'] }}"

    - name: Run all the high availability VMs
      include_tasks: tasks/recover/run_vms.yml vms={{ item }}
      with_items: "{{ running_vms_fail_back }}"
      when: item.high_availability.enabled | bool

    - name: Run all the entire running VMs
      include_tasks: tasks/recover/run_vms.yml vms={{ item }}
      with_items: "{{ running_vms_fail_back }}"
      when: not item.high_availability.enabled | bool

  ignore_errors: "{{ dr_ignore_error_clean }}"
  tags:
      - fail_back
- always:
    - name: Revoke the SSO token
      ovirt_auth:
          state: absent
          ovirt_auth: "{{ ovirt_auth }}"
